# Generated by Django 2.1.3 on 2018-12-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=255)),
                ('st_name', models.CharField(max_length=255)),
                ('st_add', models.TextField()),
                ('st_st', models.CharField(max_length=255)),
                ('st_per', models.PositiveIntegerField()),
            ],
        ),
    ]
