# Generated by Django 2.1.3 on 2018-12-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Excel', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studendata',
            name='file',
        ),
        migrations.AddField(
            model_name='studendata',
            name='files',
            field=models.FileField(default=0, upload_to='pic_folder/'),
            preserve_default=False,
        ),
    ]
